### ISSUE TITLE
Bev Facey Inspection Map

### ISSUE THREAD

**Issue by ha0511kr** [FaceyComputers/BevFacey_iOS#4]
http://www.infrastructure.alberta.ca/content/doctype354/production/reports/School/B4004A.pdf
Go to the last page.

**Comment by mickey167** [comment]
Nic, I added maps, let me know if they will work or not.  Close the ticket if this issue is solved.

**Comment by nic3-14159** [comment]
Yes, they will work, assuming they are to scale. They probably are though. I will probably edit them a bit to remove the technical specifications (I don't need to know if stairs go up or down), as well as add more descriptive labels. It is slightly out of date, (for example, there is a door from the canteen into the gym, and the renos to Cosmetology are not included), but the layout is the same and any differences can be ignored or deleted.
